spring:
  datasource:
    url: jdbc:mysql://localhost:8080/antonio_prova
    username: root
    password: password
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
