spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newdb
    username: root
    password: focamonaca
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
