spring:
  datasource:
<<<<<<<< HEAD:src/main/resources/application.yml
    url: jdbc:mysql://localhost:3306/newdb
    username: root
    password: focamonaca
    driver-class-name: com.mysql.cj.jdbc.Driver
========
    url: jdbc:mysql://localhost:8080/antonio_prova
    username: root
    password: password
>>>>>>>> feat:target/classes/application.yml
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
