spring:

  datasource:
    url: jdbc:mysql://localhost:3306/studio_medico_
    username: root
    password: Milanista1997

  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
